### ISSUE TITLE
Confusion about the time cost of GCG and AutoDAN

### ISSUE THREAD

**Issue by allblueJT** [EasyJailbreak/EasyJailbreak#14]
Hi! 

According to the paper of AutoDAN, the time cost of each iter of AutoDAN is less than GCG. But as shown in your paper of EasyJailbreak, AutoDAN cost much higher time than GCG. I'm wandering what made the difference.

Does AutoDAN require more epochs to converge than GCG? Or in your exp settings, AutoDAN is executed on 520 samples(for example) to optimize the suffix while GCG just uses 25 samples(as mentioned in the origin paper)?

**Comment by nitwtog** [comment]
This is because we tested different models, and AutoDAN's attack time increased as the difficulty of the jailbreak attack increased. In this case, AutoDAN used 50 samples, but the average time was still quite high. Additionally, the GCG in this project had some code optimizations, making it run faster compared to the original code.
