### ISSUE TITLE
Is this a small bug in the TAP seed template?

### ISSUE THREAD

**Issue by XChen-Zero** [EasyJailbreak/EasyJailbreak#21]
https://github.com/EasyJailbreak/EasyJailbreak/blob/f82a13c715627d1dee2960fa8118780a7ee731e7/easyjailbreak/seed/seed_template.json#L262

Should the {reference_responses} placeholder in TAP template be changed to {target_str}? This corresponds to the following:
https://github.com/EasyJailbreak/EasyJailbreak/blob/f82a13c715627d1dee2960fa8118780a7ee731e7/easyjailbreak/mutation/generation/IntrospectGeneration.py#L134

This modification is just my guess, I hope to get your reply.

**Comment by StarConnor** [comment]
https://github.com/EasyJailbreak/EasyJailbreak/blob/f82a13c715627d1dee2960fa8118780a7ee731e7/easyjailbreak/seed/seed_template.json#L261
Actually in attacker/TAP_Mehrotra_2023.py, the seed is iniatialized with the first element of the TAP seed strings in seed_template.json, which has "target_str" instead of "reference_responses"(show above). You can view the code of the inialization of the mutator of the TAP method(show below: `system_prompt=self.seeds[0]`).
https://github.com/EasyJailbreak/EasyJailbreak/blob/f82a13c715627d1dee2960fa8118780a7ee731e7/easyjailbreak/attacker/TAP_Mehrotra_2023.py#L97-L101
But I have to admit that it is ugly and it was not fixed during development as it affected nothing.
